services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: dazzboard_user
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_DB: dazzboarddb
    ports:
      - 5432:5432
    volumes:
      - monorepo_data:/var/lib/postgresql/data

volumes:
  db_data:
